n=input().split()
sum=0
for i in n:
    s=len(i)//2
    sum+=int(i[s])

print(sum)

## Data Analysis
- Any useful information is called data
- Types of Data in Devices
    - .txt,.img,.ppt,.mp3,.excel,.doc etc
- Types of data in realtime
    1. Quantitative data
    - Represents the size/volume of data
    -Discrete and Continuos 
    - Discrete: Data is constant/fixed
    Eg: Numbers in a dice, color, nationality etc
    - Continuos data means the value/Data is continuos
    Eg: time,height, weight
    2. Qualitative Data
        - Data is analyzed and categorized
        - Eg: Data Submission in feedback form
- Data in statistics
    - Normal, ordinal, interval and ratio
        - Nominal means data categorized on the basis of names
        - Eg: color, Nationality, Gender
        - Ordinal means data is categorized upon the order of value
        - Eg: Feedback Form
        - Interval means a range of nterval values
            - Eg: time interval in clock
        - Ratio means data is
    

In [1]:
##numpy
import numpy as np
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'Bytes0',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'Datetime64',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Str0',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'Uint64',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',

In [2]:
np.__version__

'1.20.1'

In [3]:
#numpy means numerical python
#which is used to deal with arrays and scientific
#computation
# array():- method to create

In [4]:
np.array([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

In [5]:
np.array([1,2,3,4,5],dtype="float")

array([1., 2., 3., 4., 5.])

In [6]:
a=np.array(range(1,10))
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
#print array starts from 1 to 50 skip by 2
b=np.array(range(1,51,3))
b

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49])

In [8]:
#print arraty stars from 100 to 50
c=np.array(range(100,50,-1))
c

array([100,  99,  98,  97,  96,  95,  94,  93,  92,  91,  90,  89,  88,
        87,  86,  85,  84,  83,  82,  81,  80,  79,  78,  77,  76,  75,
        74,  73,  72,  71,  70,  69,  68,  67,  66,  65,  64,  63,  62,
        61,  60,  59,  58,  57,  56,  55,  54,  53,  52,  51])

In [9]:
a.ndim

1

In [10]:
a=np.array([[1,2,3],[2,3,4]])
a

array([[1, 2, 3],
       [2, 3, 4]])

In [11]:
a.size
a.shape


(2, 3)

In [12]:
a.dtype

dtype('int32')

In [13]:
a.flatten

<function ndarray.flatten>

In [14]:
a=np.array([[[1,2,3],[1,2,3]],[[4,5,6],[4,7,8]]])
a

array([[[1, 2, 3],
        [1, 2, 3]],

       [[4, 5, 6],
        [4, 7, 8]]])

In [15]:
a.ndim

3

In [16]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [17]:
a.ndim

1

In [18]:
a[0],a[1],a[2]

(1, 2, 3)

In [19]:
a=np.array([[2,3,4],[1,2,3]])
a

array([[2, 3, 4],
       [1, 2, 3]])

In [20]:
a.ndim


2

In [21]:
a[0],a[1]

(array([2, 3, 4]), array([1, 2, 3]))

In [22]:
a[0][1]

3

In [23]:
#n dimensional array
a=np.array([1,2,3,4],ndmin=3)
a

array([[[1, 2, 3, 4]]])

In [27]:
a=np.eye(4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [28]:
a=np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [29]:
o=np.ones((3,2))
o

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [30]:
a=np.full(4,'hi')
a

array(['hi', 'hi', 'hi', 'hi'], dtype='<U2')

In [31]:
b=np.full((3,3),'hi')
b

array([['hi', 'hi', 'hi'],
       ['hi', 'hi', 'hi'],
       ['hi', 'hi', 'hi']], dtype='<U2')

In [33]:
b.fill(4)
b

array([['4', '4', '4'],
       ['4', '4', '4'],
       ['4', '4', '4']], dtype='<U2')

In [36]:
b=np.arange(25)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [38]:
##print array using arange method
#start range=20
#end range=100
#skip by 3 numbers
b=np.arange(20,100,3)
b

array([20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50, 53, 56, 59, 62, 65, 68,
       71, 74, 77, 80, 83, 86, 89, 92, 95, 98])

In [39]:
b=np.arange(100,1,-1)
b

array([100,  99,  98,  97,  96,  95,  94,  93,  92,  91,  90,  89,  88,
        87,  86,  85,  84,  83,  82,  81,  80,  79,  78,  77,  76,  75,
        74,  73,  72,  71,  70,  69,  68,  67,  66,  65,  64,  63,  62,
        61,  60,  59,  58,  57,  56,  55,  54,  53,  52,  51,  50,  49,
        48,  47,  46,  45,  44,  43,  42,  41,  40,  39,  38,  37,  36,
        35,  34,  33,  32,  31,  30,  29,  28,  27,  26,  25,  24,  23,
        22,  21,  20,  19,  18,  17,  16,  15,  14,  13,  12,  11,  10,
         9,   8,   7,   6,   5,   4,   3,   2])

In [40]:
b=np.arange(12)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [42]:
b.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [43]:
a=np.arange(100,20,-4)
a

array([100,  96,  92,  88,  84,  80,  76,  72,  68,  64,  60,  56,  52,
        48,  44,  40,  36,  32,  28,  24])

In [49]:
c=np.arange(200)
c

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [52]:
c.reshape(50,4)


array([[  0,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11],
       [ 12,  13,  14,  15],
       [ 16,  17,  18,  19],
       [ 20,  21,  22,  23],
       [ 24,  25,  26,  27],
       [ 28,  29,  30,  31],
       [ 32,  33,  34,  35],
       [ 36,  37,  38,  39],
       [ 40,  41,  42,  43],
       [ 44,  45,  46,  47],
       [ 48,  49,  50,  51],
       [ 52,  53,  54,  55],
       [ 56,  57,  58,  59],
       [ 60,  61,  62,  63],
       [ 64,  65,  66,  67],
       [ 68,  69,  70,  71],
       [ 72,  73,  74,  75],
       [ 76,  77,  78,  79],
       [ 80,  81,  82,  83],
       [ 84,  85,  86,  87],
       [ 88,  89,  90,  91],
       [ 92,  93,  94,  95],
       [ 96,  97,  98,  99],
       [100, 101, 102, 103],
       [104, 105, 106, 107],
       [108, 109, 110, 111],
       [112, 113, 114, 115],
       [116, 117, 118, 119],
       [120, 121, 122, 123],
       [124, 125, 126, 127],
       [128, 129, 130, 131],
       [132, 133, 134, 135],
       [136, 1

In [54]:
##random
c=np.random.randint(10)
c

4

In [56]:
a=np.random.randint(10,50)
a

11

In [58]:
lw,uw=int(input()),int(input())
c=np.random.randint(lw,uw,8)
c.reshape(2,4)

6
69


array([[18, 58, 51, 31],
       [46,  7, 42, 27]])

In [59]:
c=np.random.randn(4,3)
c

array([[-0.88823612, -0.20440771,  0.52600395],
       [-1.03169945,  0.77126309,  2.46746761],
       [-0.13125397,  0.16087933, -0.75626242],
       [ 1.09184224, -0.53629082, -0.00399212]])

In [61]:
c=np.linspace(1,1)
c

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [63]:
b=np.arange(20).reshape(4,5)
print(b)
print(b.transpose())

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]


In [68]:
a=np.arange(10).reshape(2,5)
print(a)
print(a[0,0:2])
print(a[1,1:3])

[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1]
[6 7]


In [73]:
## arithematic operations on arrays
a,b=np.arange(6),np.arange(6,12)
print(a,"\n",b)
x=a+b
y=a-b
z=a*b
w=a//b
print(x)
print(y)
print(z)
print(w)

[0 1 2 3 4 5] 
 [ 6  7  8  9 10 11]
[ 6  8 10 12 14 16]
[-6 -6 -6 -6 -6 -6]
[ 0  7 16 27 40 55]
[0 0 0 0 0 0]


In [74]:
a=np.log([1,2,3,4])
a

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [75]:
np.log(1)

0.0

In [77]:
a=np.sin([1,2,3,4])
a

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [78]:
#statistics
a=np.array([[1,23,78],[20,40,60]])
print(a)

[[ 1 23 78]
 [20 40 60]]


In [80]:
print(np.amin(a))
print(np.amax(a))

1
78


In [81]:
a=np.array([5,6,7])
print(np.mean(a))

6.0


In [82]:
print(np.median(a))

6.0


In [83]:
#standard deviation
## square root of average of square deviation os mean
print(np.std(a))

0.816496580927726


In [84]:
##variance
#average of squares of standard deviation
print(np.var(a))

0.6666666666666666


In [85]:
##aggregation
np.sum(a)

18

In [86]:
np.average(b)

8.5

In [87]:
np.prod(c)

1.0

In [88]:
m=np.random.random((3,4))
print(m)

[[0.94605516 0.22839866 0.22797393 0.46874226]
 [0.55316685 0.86495287 0.94289185 0.20974669]
 [0.62498253 0.77829711 0.76983615 0.81492088]]


In [91]:
np.min(a)


5

In [90]:
np.max(a)

7

In [92]:
#filtering
a=np.array([41,42,43,44,45])
f=a>42
n=a[f]
print(f)
print(n)

[False False  True  True  True]
[43 44 45]


In [93]:
b=np.array([24,31,34,56,21])
f=b%2==0
n=b[f]
print(n)

[24 34 56]


In [94]:
## saving the data

In [96]:
from numpy import asarray
from numpy import savetxt
data=np.array([[1,2,3,4],[5,6,7,8]])
savetxt('data.csv',data,delimiter=",")

In [97]:
## displaying the data from .csv file
from numpy import loadtxt
data=loadtxt('data.csv',delimiter=",")
data

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])